version: '3'

services:
  web:
    build: .
    command: yarn serve # <- Important!
    volumes:
      - .:/usr/src/todo-in-vue
    expose:
      - "8080"
    ports:
      - "8080:8080"

# Notify container when file changes on windows
# https://github.com/ITISFoundation/osparc-simcore/issues/93
# pip install docker-windows-volume-watcher
# docker-volume-watcher